apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: null
  generation: 1
  labels:
    run: tasks-mysql
  name: tasks-mysql
  selfLink: /apis/extensions/v1beta1/namespaces//deployments/tasks-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      run: tasks-mysql
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: tasks-mysql
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: forge
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: "true"
        - name: MYSQL_PASSWORD
          value: forge
        - name: MYSQL_USER
          value: forge
        image: mysql:5.7
        imagePullPolicy: IfNotPresent
        name: tasks-mysql
        ports:
        - containerPort: 3306
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
