apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: general-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "gce"
spec:
  tls:
  - hosts:
    - tasks.zoidbergwill.com
    secretName: tasks-tls
  rules:
  - host: tasks.zoidbergwill.com
    http:
      paths:
      - path: /
        backend:
          serviceName: tasks-app
          servicePort: 80
